on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - devel
  schedule:
    - cron: '0 9 * * 4'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.image }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc }} - ${{ matrix.config.image }})

    strategy:
      fail-fast: false
      matrix:
        config:
        ## For macOS, explicitly use newer miniconda (where DYLD_FALLBACK_LIBRARY_PATH is unset
        ## in the installation script) than the one used by basilisk
        - { os: macOS-latest, bioc: 'devel', miniconda: 'py39_22.11.1-1'}
        - { os: macos-14, bioc: 'devel', miniconda: 'py39_22.11.1-1'}
        - { os: windows-latest, bioc: 'devel', miniconda: 'py39_4.12.0'}
        - { os: ubuntu-latest, bioc: 'devel', miniconda: 'py39_4.12.0', image: "bioconductor/bioconductor_docker:devel", cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BASILISK_MINICONDA_VERSION: ${{ matrix.config.miniconda }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        if: matrix.config.image == null
        with:
          bioc-version: ${{ matrix.config.bioc }}

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
        if: matrix.config.image == null

      - name: Unset DYLD_FALLBACK_LIBRARY_PATH
        if: runner.os == 'macOS'
        run: unset DYLD_FALLBACK_LIBRARY_PATH

      - name: Install remotes
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows' && matrix.config.image == null
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-bioc-${{ matrix.config.bioc }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ matrix.config.os }}-bioc-${{ matrix.config.bioc }}-

      - name: Update apt-get
        if: runner.os == 'Linux'
        run: sudo apt-get update

      - name: Install system dependencis (Linux)
        if: runner.os == 'Linux'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            extra-packages: any::rcmdcheck
            pak-version: devel

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install harfbuzz
          brew install fribidi
          brew install openssl

      ## make sure that crypto is found (suggestion from https://github.com/schienstockd/cecelia)
      - name: Install dependencies (macos-14)
        if: matrix.config.os == 'macos-14'
        env:
            LIBRARY_PATH: '/opt/homebrew/lib'
            LDFLAGS: '-L/opt/homebrew/lib'
            CPPFLAGS: '-I/opt/homebrew/include'
        run: |
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
          remotes::install_cran('rcmdcheck', Ncpu = 2L)
        shell: Rscript {0}

      - name: Install dependencies
        if: matrix.config.os != 'macos-14'
        run: |
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
          remotes::install_cran('rcmdcheck', Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check DYLD_FALLBACK_LIBRARY_PATH
        if: runner.os == 'macOS'
        run: echo $DYLD_FALLBACK_LIBRARY_PATH

      - name: Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          arguments: '--no-check-bioc-views --no-check-bioc-help'
          error-on: 'error'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-bioc${{ matrix.config.bioc }}-results
          path: check

      - name: Test coverage
        if: matrix.config.os == 'macOS-latest'
        run: |
          install.packages("covr")
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/devel' && matrix.config.os == 'macOS-latest'
        run: |
          R CMD INSTALL .
          Rscript -e "remotes::install_dev('pkgdown'); pkgdown::deploy_to_branch(new_process = FALSE)"
